function [torque_body, force_body] = aerodynamic_torque( ...
    relative_velocity_inertial, ...
    quaternion, ...
    atmospheric_density, ...
    drag_coefficient, ...
    reference_area, ...
    centre_of_pressure_offset_body)
%AERODYNAMIC_TORQUE Calculate simplified aerodynamic disturbance.
%
% Inputs:
%   relative_velocity_inertial      - velocity relative to atmosphere, m/s
%   quaternion                     - body-to-inertial quaternion
%   atmospheric_density            - atmospheric density, kg/m^3
%   drag_coefficient               - dimensionless
%   reference_area                 - effective area, m^2
%   centre_of_pressure_offset_body - CP relative to COM, body axes, m
%
% Outputs:
%   torque_body - aerodynamic torque in body axes, N m
%   force_body  - aerodynamic force in body axes, N

relative_speed = norm(relative_velocity_inertial);

if relative_speed < 1e-12
    force_body = [0; 0; 0];
    torque_body = [0; 0; 0];
    return;
end

%% Drag force in inertial coordinates
drag_force_inertial = ...
    -0.5 ...
    * atmospheric_density ...
    * drag_coefficient ...
    * reference_area ...
    * relative_speed ...
    * relative_velocity_inertial;

%% Convert force to body coordinates
body_to_inertial = ...
    quaternion_to_rotation_matrix(quaternion);

force_body = ...
    body_to_inertial.' * drag_force_inertial;

%% Torque about centre of mass
torque_body = cross( ...
    centre_of_pressure_offset_body, ...
    force_body);

end