%% Build Three-Axis Quaternion Simulink Model

clear;
clc;

%% Load model parameters into the base workspace
init_simulink_3axis;

model_name = 'cubesat_attitude_3axis';

%% Protect any existing model
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if isfile([model_name, '.slx'])
    error([model_name, '.slx already exists. ', ...
        'Rename or move it before rebuilding.']);
end

%% Create model
new_system(model_name);
open_system(model_name);

%% Add state integrator
add_block( ...
    'simulink/Continuous/Integrator', ...
    [model_name, '/Spacecraft State'], ...
    'InitialCondition', 'initial_state_3axis', ...
    'Position', [760, 250, 800, 290]);

%% Add parameter constants
add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Command Quaternion'], ...
    'Value', 'command_quaternion_3axis', ...
    'Position', [80, 80, 180, 110]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Inertia Matrix'], ...
    'Value', 'I', ...
    'Position', [80, 135, 180, 165]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Kp'], ...
    'Value', 'Kp_3axis', ...
    'Position', [80, 190, 180, 220]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Kd'], ...
    'Value', 'Kd_3axis', ...
    'Position', [80, 245, 180, 275]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Wheel Inertia'], ...
    'Value', 'wheel_inertia', ...
    'Position', [80, 300, 180, 330]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Torque Limit'], ...
    'Value', 'wheel_torque_max', ...
    'Position', [80, 355, 180, 385]);

add_block( ...
    'simulink/Sources/Constant', ...
    [model_name, '/Speed Limit'], ...
    'Value', 'wheel_speed_max', ...
    'Position', [80, 410, 180, 440]);

%% Add combined controller and dynamics block
dynamics_path = ...
    [model_name, '/Quaternion ADCS Dynamics'];

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function', ...
    dynamics_path, ...
    'Position', [350, 175, 620, 365]);

%% Insert MATLAB Function block code
stateflow_root = sfroot;

chart = find( ...
    stateflow_root, ...
    '-isa', 'Stateflow.EMChart', ...
    'Path', dynamics_path);

chart.Script = sprintf([ ...
'function [state_dot, applied_torque, wheel_speed, quaternion_norm] = fcn(state, command_quaternion, inertia_matrix, Kp, Kd, wheel_inertia, torque_limit, speed_limit)\n' ...
'%%#codegen\n' ...
'\n' ...
'quaternion = state(1:4);\n' ...
'body_rate = state(5:7);\n' ...
'wheel_speed = state(8:10);\n' ...
'\n' ...
'[~, requested_torque] = pd_controller_quaternion( ...\n' ...
'    command_quaternion, quaternion, body_rate, ...\n' ...
'    Kp, Kd, torque_limit);\n' ...
'\n' ...
'[applied_torque, wheel_acceleration] = ...\n' ...
'    reaction_wheel_actuator( ...\n' ...
'        requested_torque, wheel_speed, ...\n' ...
'        wheel_inertia, torque_limit, speed_limit);\n' ...
'\n' ...
'quaternion_dot = quaternion_kinematics( ...\n' ...
'    quaternion, body_rate);\n' ...
'\n' ...
'total_body_momentum = ...\n' ...
'    inertia_matrix * body_rate ...\n' ...
'    + wheel_inertia .* wheel_speed;\n' ...
'\n' ...
'body_rate_dot = inertia_matrix \\ ( ...\n' ...
'    applied_torque ...\n' ...
'    - cross(body_rate, total_body_momentum));\n' ...
'\n' ...
'state_dot = [ ...\n' ...
'    quaternion_dot; ...\n' ...
'    body_rate_dot; ...\n' ...
'    wheel_acceleration];\n' ...
'\n' ...
'quaternion_norm = sqrt(sum(quaternion.^2));\n' ...
'end\n']);

%% Add result blocks
add_block( ...
    'simulink/Sinks/Scope', ...
    [model_name, '/State Scope'], ...
    'Position', [1000, 235, 1035, 285]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [model_name, '/State Output'], ...
    'VariableName', 'state_3axis_out', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [900, 320, 1010, 350]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [model_name, '/Torque Output'], ...
    'VariableName', 'torque_3axis_out', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [700, 100, 820, 130]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [model_name, '/Wheel Speed Output'], ...
    'VariableName', 'wheel_speed_3axis_out', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [700, 145, 840, 175]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [model_name, '/Quaternion Norm Output'], ...
    'VariableName', 'quaternion_norm_3axis_out', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [700, 395, 860, 425]);

%% Connect feedback and parameter signals
add_line( ...
    model_name, ...
    'Spacecraft State/1', ...
    'Quaternion ADCS Dynamics/1', ...
    'autorouting', 'on');

add_line( ...
    model_name, ...
    'Quaternion ADCS Dynamics/1', ...
    'Spacecraft State/1', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Command Quaternion/1', ...
    'Quaternion ADCS Dynamics/2', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Inertia Matrix/1', ...
    'Quaternion ADCS Dynamics/3', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Kp/1', ...
    'Quaternion ADCS Dynamics/4', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Kd/1', ...
    'Quaternion ADCS Dynamics/5', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Wheel Inertia/1', ...
    'Quaternion ADCS Dynamics/6', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Torque Limit/1', ...
    'Quaternion ADCS Dynamics/7', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Speed Limit/1', ...
    'Quaternion ADCS Dynamics/8', ...
    'autorouting', 'on');

%% Connect outputs
add_line(model_name, ...
    'Spacecraft State/1', ...
    'State Scope/1', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Spacecraft State/1', ...
    'State Output/1', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Quaternion ADCS Dynamics/2', ...
    'Torque Output/1', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Quaternion ADCS Dynamics/3', ...
    'Wheel Speed Output/1', ...
    'autorouting', 'on');

add_line(model_name, ...
    'Quaternion ADCS Dynamics/4', ...
    'Quaternion Norm Output/1', ...
    'autorouting', 'on');

%% Solver settings
set_param( ...
    model_name, ...
    'Solver', 'ode45', ...
    'StopTime', 'simulation_duration_3axis', ...
    'RelTol', '1e-8', ...
    'AbsTol', '1e-10', ...
    'ReturnWorkspaceOutputs', 'on');

%% Arrange and save
Simulink.BlockDiagram.arrangeSystem(model_name);

save_system( ...
    model_name, ...
    [model_name, '.slx']);

open_system(model_name);

fprintf('\nCreated %s.slx successfully.\n', ...
    model_name);