function state_dot = closed_loop_dynamics_quaternion( ...
    time, state, command_quaternion, ...
    Kp, Kd, tau_max, I)
%CLOSED_LOOP_DYNAMICS_QUATERNION Quaternion controller and spacecraft plant.
%
% State:
%   state(1:4) = quaternion [qw; qx; qy; qz]
%   state(5:7) = body rates [p; q; r] in rad/s

current_quaternion = state(1:4);
omega = state(5:7);

% Normalize before calculating attitude error.
current_quaternion = ...
    current_quaternion / norm(current_quaternion);

tau = pd_controller_quaternion( ...
    command_quaternion, ...
    current_quaternion, ...
    omega, ...
    Kp, ...
    Kd, ...
    tau_max);

state_for_dynamics = [current_quaternion; omega];

state_dot = spacecraft_dynamics_quaternion( ...
    time, state_for_dynamics, tau, I);

end