function state_dot = closed_loop_dynamics_reaction_wheels( ...
    time, state, command_quaternion, Kp, Kd, I, ...
    wheel_inertia, wheel_torque_max, wheel_speed_max)
%CLOSED_LOOP_DYNAMICS_REACTION_WHEELS
% Quaternion controller, reaction wheels, and spacecraft dynamics.
%
% State:
%   state(1:4)  = quaternion
%   state(5:7)  = spacecraft body rates
%   state(8:10) = reaction-wheel speeds

current_quaternion = state(1:4);
omega = state(5:7);

current_quaternion = ...
    current_quaternion / norm(current_quaternion);

%% Calculate the controller's requested spacecraft torque
% The reaction-wheel actuator applies the physical limits.
[~, requested_spacecraft_torque] = ...
    pd_controller_quaternion( ...
        command_quaternion, ...
        current_quaternion, ...
        omega, ...
        Kp, ...
        Kd, ...
        wheel_torque_max);

%% Propagate spacecraft and wheel states
state_dot = spacecraft_dynamics_reaction_wheels( ...
    time, ...
    state, ...
    requested_spacecraft_torque, ...
    I, ...
    wheel_inertia, ...
    wheel_torque_max, ...
    wheel_speed_max);

end