function [total_torque, components] = ...
    combined_environmental_torque( ...
        position_inertial, ...
        velocity_inertial, ...
        quaternion, ...
        I, ...
        environment)
%COMBINED_ENVIRONMENTAL_TORQUE
% Calculate gravity-gradient, aerodynamic, SRP, and magnetic torque.
%
% Outputs:
%   total_torque - sum of all disturbance torques in body axes
%   components   - structure containing each individual torque

%% Gravity-gradient torque
components.gravity_gradient = gravity_gradient_torque( ...
    position_inertial, ...
    quaternion, ...
    I, ...
    environment.mu);

%% Aerodynamic torque
components.aerodynamic = aerodynamic_torque( ...
    velocity_inertial, ...
    quaternion, ...
    environment.atmospheric_density, ...
    environment.drag_coefficient, ...
    environment.aerodynamic_area, ...
    environment.aerodynamic_cp_offset_body);

%% Solar-radiation-pressure torque
components.srp = solar_radiation_pressure_torque( ...
    environment.sun_direction_inertial, ...
    quaternion, ...
    environment.solar_pressure, ...
    environment.reflectivity_coefficient, ...
    environment.illuminated_area, ...
    environment.solar_cp_offset_body, ...
    environment.illumination_factor);

%% Earth magnetic field
magnetic_field_inertial = earth_dipole_field( ...
    position_inertial, ...
    environment.earth_radius, ...
    environment.equatorial_surface_field, ...
    environment.dipole_axis_inertial);

%% Magnetic disturbance torque
components.magnetic = magnetic_disturbance_torque( ...
    environment.residual_dipole_body, ...
    magnetic_field_inertial, ...
    quaternion);

components.magnetic_field_inertial = ...
    magnetic_field_inertial;

%% Total disturbance torque
total_torque = ...
    components.gravity_gradient ...
    + components.aerodynamic ...
    + components.srp ...
    + components.magnetic;

end