function magnetic_field_inertial = earth_dipole_field( ...
    position_inertial, ...
    earth_radius, ...
    equatorial_surface_field, ...
    dipole_axis_inertial)
%EARTH_DIPOLE_FIELD Simplified centred Earth magnetic dipole.
%
% Inputs:
%   position_inertial        - Earth-centred position vector [m]
%   earth_radius             - Earth radius [m]
%   equatorial_surface_field - equatorial surface field [T]
%   dipole_axis_inertial     - unit magnetic dipole axis
%
% Output:
%   magnetic_field_inertial  - magnetic field vector [T]

orbital_radius = norm(position_inertial);

radial_unit = ...
    position_inertial / orbital_radius;

dipole_axis = ...
    dipole_axis_inertial / norm(dipole_axis_inertial);

radial_scale = ...
    (earth_radius / orbital_radius)^3;

magnetic_field_inertial = ...
    equatorial_surface_field ...
    * radial_scale ...
    * ( ...
        3 * dot(dipole_axis, radial_unit) ...
        * radial_unit ...
        - dipole_axis ...
      );

end