function [quaternion_updated, bias_updated, ...
    covariance_updated, innovation] = mekf_update( ...
        quaternion_predicted, ...
        bias_predicted, ...
        covariance_predicted, ...
        measured_quaternion, ...
        star_tracker_noise_std)
%MEKF_UPDATE Correct the attitude and gyro-bias estimates.
%
% The six-component error state is:
%   [three-component attitude error;
%    three-component gyro-bias error]

quaternion_predicted = ...
    quaternion_predicted / norm(quaternion_predicted);

measured_quaternion = ...
    measured_quaternion / norm(measured_quaternion);

%% Quaternion measurement residual
measurement_error_quaternion = quaternion_error( ...
    measured_quaternion, ...
    quaternion_predicted);

% Small-angle rotation-vector innovation
innovation = ...
    2 * measurement_error_quaternion(2:4);

%% Measurement model
measurement_matrix = [
    eye(3), zeros(3)
];

measurement_noise_covariance = ...
    star_tracker_noise_std^2 * eye(3);

innovation_covariance = ...
    measurement_matrix ...
    * covariance_predicted ...
    * measurement_matrix.' ...
    + measurement_noise_covariance;

kalman_gain = ...
    covariance_predicted ...
    * measurement_matrix.' ...
    / innovation_covariance;

%% Error-state correction
error_state_correction = ...
    kalman_gain * innovation;

attitude_correction = ...
    error_state_correction(1:3);

bias_correction = ...
    error_state_correction(4:6);

correction_quaternion = ...
    rotation_vector_to_quaternion( ...
        attitude_correction);

quaternion_updated = quaternion_multiply( ...
    quaternion_predicted, ...
    correction_quaternion);

quaternion_updated = ...
    quaternion_updated / norm(quaternion_updated);

bias_updated = ...
    bias_predicted + bias_correction;

%% Joseph covariance update
identity_matrix = eye(6);

joseph_factor = ...
    identity_matrix ...
    - kalman_gain * measurement_matrix;

covariance_updated = ...
    joseph_factor ...
    * covariance_predicted ...
    * joseph_factor.' ...
    + kalman_gain ...
    * measurement_noise_covariance ...
    * kalman_gain.';

%% Reset covariance after injecting the attitude correction
correction_skew = [
     0,                      -attitude_correction(3),  attitude_correction(2);
     attitude_correction(3),  0,                     -attitude_correction(1);
    -attitude_correction(2),  attitude_correction(1),  0
];

reset_matrix = [
    eye(3) - 0.5 * correction_skew, zeros(3);
    zeros(3),                       eye(3)
];

covariance_updated = ...
    reset_matrix ...
    * covariance_updated ...
    * reset_matrix.';

covariance_updated = 0.5 * ( ...
    covariance_updated + covariance_updated.');

end