function [drag_acceleration, relative_velocity] = ...
    orbital_drag_acceleration( ...
        position_inertial, ...
        velocity_inertial, ...
        spacecraft_mass, ...
        atmospheric_density, ...
        drag_coefficient, ...
        reference_area, ...
        earth_rotation_rate)
%ORBITAL_DRAG_ACCELERATION Calculate acceleration due to atmospheric drag.
%
% Inputs:
% position_inertial     - inertial position [m]
% velocity_inertial     - inertial spacecraft velocity [m/s]
% spacecraft_mass       - spacecraft mass [kg]
% atmospheric_density   - atmospheric density [kg/m^3]
% drag_coefficient      - dimensionless
% reference_area        - area normal to flow [m^2]
% earth_rotation_rate   - Earth rotation rate [rad/s]
%
% Outputs:
% drag_acceleration     - inertial drag acceleration [m/s^2]
% relative_velocity     - velocity relative to atmosphere [m/s]

earth_angular_velocity = [
    0;
    0;
    earth_rotation_rate
];

atmospheric_velocity = cross( ...
    earth_angular_velocity, ...
    position_inertial);

relative_velocity = ...
    velocity_inertial - atmospheric_velocity;

relative_speed = norm(relative_velocity);

if relative_speed == 0
    drag_acceleration = [0; 0; 0];
    return;
end

drag_acceleration = ...
    -0.5 ...
    * atmospheric_density ...
    * drag_coefficient ...
    * reference_area ...
    / spacecraft_mass ...
    * relative_speed ...
    * relative_velocity;

end