function [semi_major_axis, eccentricity, inclination, ...
    right_ascension, argument_of_periapsis, ...
    true_anomaly] = orbital_elements_from_state( ...
        position, velocity, mu)
%ORBITAL_ELEMENTS_FROM_STATE Convert Cartesian state to orbital elements.
%
% Angular outputs are in radians.

radius = norm(position);
speed = norm(velocity);

angular_momentum = cross(position, velocity);
angular_momentum_magnitude = norm(angular_momentum);

reference_axis = [0; 0; 1];

node_vector = cross( ...
    reference_axis, ...
    angular_momentum);

node_magnitude = norm(node_vector);

eccentricity_vector = ...
    cross(velocity, angular_momentum) / mu ...
    - position / radius;

eccentricity = norm(eccentricity_vector);

specific_energy = ...
    0.5 * speed^2 - mu / radius;

semi_major_axis = ...
    -mu / (2 * specific_energy);

inclination = acos(max(-1, min(1, ...
    angular_momentum(3) ...
    / angular_momentum_magnitude)));

tolerance = 1e-10;

%% Right ascension of ascending node
if node_magnitude > tolerance
    right_ascension = atan2( ...
        node_vector(2), ...
        node_vector(1));

    right_ascension = mod( ...
        right_ascension, 2*pi);
else
    right_ascension = 0;
end

%% Argument of periapsis
if eccentricity > tolerance ...
        && node_magnitude > tolerance

    argument_of_periapsis = acos( ...
        max(-1, min(1, ...
        dot(node_vector, eccentricity_vector) ...
        / (node_magnitude * eccentricity))));

    if eccentricity_vector(3) < 0
        argument_of_periapsis = ...
            2*pi - argument_of_periapsis;
    end
else
    argument_of_periapsis = 0;
end

%% True anomaly
if eccentricity > tolerance
    true_anomaly = acos( ...
        max(-1, min(1, ...
        dot(eccentricity_vector, position) ...
        / (eccentricity * radius))));

    if dot(position, velocity) < 0
        true_anomaly = 2*pi - true_anomaly;
    end

elseif node_magnitude > tolerance
    % Circular inclined orbit: use argument of latitude.
    true_anomaly = atan2( ...
        dot(cross(node_vector, position), ...
            angular_momentum) ...
            / (node_magnitude ...
            * radius ...
            * angular_momentum_magnitude), ...
        dot(node_vector, position) ...
            / (node_magnitude * radius));

    true_anomaly = mod(true_anomaly, 2*pi);

else
    % Circular equatorial orbit: use inertial longitude.
    true_anomaly = mod( ...
        atan2(position(2), position(1)), ...
        2*pi);
end

end