function next_state = rk4_orbit_j2_drag_step( ...
    state, ...
    sample_time, ...
    mu, ...
    earth_radius, ...
    J2, ...
    spacecraft_mass, ...
    atmospheric_density, ...
    drag_coefficient, ...
    reference_area, ...
    earth_rotation_rate)
%RK4_ORBIT_J2_DRAG_STEP Propagate an orbit with J2 and drag.
%
% State format:
% state(1:3) = inertial position [m]
% state(4:6) = inertial velocity [m/s]

state_derivative = @(current_state) ...
    orbit_state_derivative( ...
        current_state, ...
        mu, ...
        earth_radius, ...
        J2, ...
        spacecraft_mass, ...
        atmospheric_density, ...
        drag_coefficient, ...
        reference_area, ...
        earth_rotation_rate);

k1 = state_derivative(state);

k2 = state_derivative( ...
    state + 0.5 * sample_time * k1);

k3 = state_derivative( ...
    state + 0.5 * sample_time * k2);

k4 = state_derivative( ...
    state + sample_time * k3);

next_state = state ...
    + sample_time / 6 ...
    * (k1 + 2*k2 + 2*k3 + k4);

end


function state_dot = orbit_state_derivative( ...
    state, ...
    mu, ...
    earth_radius, ...
    J2, ...
    spacecraft_mass, ...
    atmospheric_density, ...
    drag_coefficient, ...
    reference_area, ...
    earth_rotation_rate)

position = state(1:3);
velocity = state(4:6);

gravity_acceleration = orbital_acceleration_j2( ...
    position, ...
    mu, ...
    earth_radius, ...
    J2);

drag_acceleration = orbital_drag_acceleration( ...
    position, ...
    velocity, ...
    spacecraft_mass, ...
    atmospheric_density, ...
    drag_coefficient, ...
    reference_area, ...
    earth_rotation_rate);

total_acceleration = ...
    gravity_acceleration + drag_acceleration;

state_dot = [
    velocity;
    total_acceleration
];

end