function next_state = rk4_reaction_wheel_step( ...
    current_state, requested_spacecraft_torque, ...
    sample_time, I, wheel_inertia, ...
    wheel_torque_max, wheel_speed_max)
%RK4_REACTION_WHEEL_STEP Propagate the ten-state spacecraft model
% by one fixed time step while holding commanded torque constant.

dynamics = @(state) ...
    spacecraft_dynamics_reaction_wheels( ...
        0, ...
        state, ...
        requested_spacecraft_torque, ...
        I, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max);

k1 = dynamics(current_state);

k2 = dynamics( ...
    current_state + 0.5 * sample_time * k1);

k3 = dynamics( ...
    current_state + 0.5 * sample_time * k2);

k4 = dynamics( ...
    current_state + sample_time * k3);

next_state = current_state ...
    + (sample_time / 6) ...
    * (k1 + 2*k2 + 2*k3 + k4);

% Enforce the unit-quaternion constraint.
next_state(1:4) = ...
    next_state(1:4) / norm(next_state(1:4));

end