function next_state = ...
    rk4_reaction_wheel_disturbed_step( ...
        current_state, ...
        requested_spacecraft_torque, ...
        external_torque, ...
        sample_time, ...
        I, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max)
%RK4_REACTION_WHEEL_DISTURBED_STEP
% Propagate the spacecraft, wheels, and external torque through
% one fixed RK4 time step.

dynamics = @(state) ...
    spacecraft_dynamics_reaction_wheels_disturbed( ...
        0, ...
        state, ...
        requested_spacecraft_torque, ...
        external_torque, ...
        I, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max);

k1 = dynamics(current_state);

k2 = dynamics( ...
    current_state + 0.5 * sample_time * k1);

k3 = dynamics( ...
    current_state + 0.5 * sample_time * k2);

k4 = dynamics( ...
    current_state + sample_time * k3);

next_state = current_state ...
    + (sample_time / 6) ...
    * (k1 + 2*k2 + 2*k3 + k4);

next_state(1:4) = ...
    next_state(1:4) / norm(next_state(1:4));

end