function next_state = rk4_orbit_j2_step( ...
    state, sample_time, mu, earth_radius, J2)
%RK4_ORBIT_J2_STEP Propagate position and velocity using RK4.
%
% State format:
% state(1:3) = inertial position [m]
% state(4:6) = inertial velocity [m/s]

    state_derivative = @(current_state) [
        current_state(4:6);
        orbital_acceleration_j2( ...
            current_state(1:3), ...
            mu, ...
            earth_radius, ...
            J2)
    ];

    k1 = state_derivative(state);

    k2 = state_derivative( ...
        state + 0.5 * sample_time * k1);

    k3 = state_derivative( ...
        state + 0.5 * sample_time * k2);

    k4 = state_derivative( ...
        state + sample_time * k3);

    next_state = state ...
        + sample_time / 6 ...
        * (k1 + 2*k2 + 2*k3 + k4);
end