function [quaternion_estimate_history, ...
    bias_estimate_history, covariance_diagonal_history, ...
    innovation_history] = run_mekf( ...
        gyro_measurements, ...
        star_tracker_measurements, ...
        sample_time, ...
        gyro_noise_std, ...
        bias_random_walk, ...
        star_tracker_noise_std, ...
        initial_quaternion_estimate, ...
        initial_bias_estimate, ...
        initial_covariance)
%RUN_MEKF Run a multiplicative extended Kalman filter.
%
% Gyro measurements are available at every time step.
% Rows containing NaN in star_tracker_measurements indicate that
% no star-tracker update is available at that time.

number_of_samples = size(gyro_measurements, 1);

quaternion_estimate_history = ...
    zeros(number_of_samples, 4);

bias_estimate_history = ...
    zeros(number_of_samples, 3);

covariance_diagonal_history = ...
    zeros(number_of_samples, 6);

innovation_history = ...
    NaN(number_of_samples, 3);

quaternion_estimate = ...
    initial_quaternion_estimate ...
    / norm(initial_quaternion_estimate);

bias_estimate = initial_bias_estimate;
covariance = initial_covariance;

for k = 1:number_of_samples
    %% Propagate from the previous sample
    if k > 1
        [quaternion_estimate, ...
         bias_estimate, ...
         covariance] = mekf_propagate( ...
            quaternion_estimate, ...
            bias_estimate, ...
            covariance, ...
            gyro_measurements(k-1,:).', ...
            sample_time, ...
            gyro_noise_std, ...
            bias_random_walk);
    end

    %% Correct when a star-tracker measurement is available
    star_tracker_available = all( ...
        isfinite(star_tracker_measurements(k,:)));

    if star_tracker_available
        [quaternion_estimate, ...
         bias_estimate, ...
         covariance, ...
         innovation] = mekf_update( ...
            quaternion_estimate, ...
            bias_estimate, ...
            covariance, ...
            star_tracker_measurements(k,:).', ...
            star_tracker_noise_std);

        innovation_history(k,:) = innovation.';
    end

    %% Store estimates
    quaternion_estimate_history(k,:) = ...
        quaternion_estimate.';

    bias_estimate_history(k,:) = ...
        bias_estimate.';

    covariance_diagonal_history(k,:) = ...
        diag(covariance).';
end

end