%% Monte Carlo Test of Sensor, MEKF and Attitude Control

clear;
clc;
close all;

%% Load nominal parameters
init_attitude_3axis_asymmetric;
init_reaction_wheels;
init_sensor_models;

%% Nominal controller gains
reference_inertia = 0.00666666666666667;
reference_Kp = 0.0067;
reference_Kd = 0.0107;

principal_inertia = diag(I);

nominal_Kp = reference_Kp ...
    * principal_inertia / reference_inertia;

nominal_Kd = reference_Kd ...
    * principal_inertia / reference_inertia;

%% Monte Carlo settings
number_of_cases = 100;
simulation_duration = 20;

rng(84);

%% Allocate results
final_control_error_deg = ...
    zeros(number_of_cases, 1);

final_estimation_error_deg = ...
    zeros(number_of_cases, 1);

rms_estimation_error_deg = ...
    zeros(number_of_cases, 1);

settling_time = ...
    NaN(number_of_cases, 1);

maximum_wheel_speed_rpm = ...
    zeros(number_of_cases, 3);

final_bias_error_deg_s = ...
    zeros(number_of_cases, 3);

speed_limit_activated = ...
    false(number_of_cases, 3);

initial_attitude_history = ...
    zeros(number_of_cases, 3);

%% Run cases
for case_number = 1:number_of_cases
    %% Initial-attitude uncertainty
    initial_attitude_case = ...
        [30; -20; 15] ...
        + 5 * (2*rand(3,1) - 1);

    %% Spacecraft-inertia uncertainty: +/-10 percent
    inertia_scale = ...
        0.9 + 0.2 * rand(3,1);

    inertia_case = diag( ...
        diag(I) .* inertia_scale);

    %% Reaction-wheel inertia uncertainty: +/-10 percent
    wheel_inertia_case = ...
        wheel_inertia ...
        .* (0.9 + 0.2 * rand(3,1));

    %% Reaction-wheel torque uncertainty: +/-10 percent
    wheel_torque_case = ...
        wheel_torque_max ...
        .* (0.9 + 0.2 * rand(3,1));

    %% Initial gyro-bias uncertainty
    gyro_bias_case = ...
        gyro_bias_initial ...
        + deg2rad(0.02) ...
        * (2*rand(3,1) - 1);

    %% Sensor-noise uncertainty: +/-20 percent
    gyro_noise_case = ...
        gyro_noise_std ...
        * (0.8 + 0.4*rand);

    bias_random_walk_case = ...
        gyro_bias_random_walk ...
        * (0.8 + 0.4*rand);

    star_tracker_noise_case = ...
        star_tracker_noise_std ...
        * (0.8 + 0.4*rand);

    %% Initial estimator error
    initial_estimation_error_case = ...
        3 * (2*rand(3,1) - 1);

    %% Run complete noisy closed-loop case
    case_results = simulate_estimated_state_case( ...
        initial_attitude_case, ...
        inertia_case, ...
        nominal_Kp, ...
        nominal_Kd, ...
        wheel_inertia_case, ...
        wheel_torque_case, ...
        wheel_speed_max, ...
        gyro_bias_case, ...
        gyro_noise_case, ...
        bias_random_walk_case, ...
        star_tracker_noise_case, ...
        gyro_sample_time, ...
        star_tracker_sample_time, ...
        simulation_duration, ...
        initial_estimation_error_case);

    %% Store results
    initial_attitude_history(case_number,:) = ...
        initial_attitude_case.';

    final_control_error_deg(case_number) = ...
        case_results.final_control_error_deg;

    final_estimation_error_deg(case_number) = ...
        case_results.final_estimation_error_deg;

    rms_estimation_error_deg(case_number) = ...
        case_results.rms_estimation_error_deg;

    settling_time(case_number) = ...
        case_results.settling_time;

    maximum_wheel_speed_rpm(case_number,:) = ...
        case_results.maximum_wheel_speed_rpm;

    final_bias_error_deg_s(case_number,:) = ...
        case_results.final_bias_error_deg_s.';

    speed_limit_activated(case_number,:) = ...
        case_results.speed_limit_activated;
end

%% Success criteria
successful_case = ...
    final_control_error_deg <= 0.5 ...
    & final_estimation_error_deg <= 0.1 ...
    & isfinite(settling_time) ...
    & ~any(speed_limit_activated, 2);

success_rate_percent = ...
    100 * mean(successful_case);

valid_settling_times = ...
    settling_time(isfinite(settling_time));

maximum_wheel_speed_all_cases = ...
    max(maximum_wheel_speed_rpm, [], 1);

number_of_speed_limit_cases = ...
    sum(any(speed_limit_activated, 2));

bias_error_magnitude = vecnorm( ...
    final_bias_error_deg_s, 2, 2);

%% Identify worst cases
[worst_control_error, worst_control_case] = ...
    max(final_control_error_deg);

[worst_estimation_error, worst_estimation_case] = ...
    max(final_estimation_error_deg);

%% Display results
fprintf('\nEstimated-state Monte Carlo results:\n');

fprintf('Number of cases: %d\n', ...
    number_of_cases);

fprintf('Successful cases: %d\n', ...
    sum(successful_case));

fprintf('Success rate: %.1f percent\n', ...
    success_rate_percent);

fprintf('\nFinal control error [deg]:\n');
fprintf('Mean: %.6f\n', ...
    mean(final_control_error_deg));
fprintf('Worst: %.6f\n', ...
    worst_control_error);

fprintf('\nFinal estimation error [deg]:\n');
fprintf('Mean: %.6f\n', ...
    mean(final_estimation_error_deg));
fprintf('Worst: %.6f\n', ...
    worst_estimation_error);

fprintf('\nRMS estimation error [deg]:\n');
fprintf('Mean: %.6f\n', ...
    mean(rms_estimation_error_deg));
fprintf('Worst: %.6f\n', ...
    max(rms_estimation_error_deg));

fprintf('\nSettling time [s]:\n');
fprintf('Mean: %.3f\n', ...
    mean(valid_settling_times));
fprintf('Worst: %.3f\n', ...
    max(valid_settling_times));

fprintf('\nMaximum wheel speed [rpm]:\n');
fprintf('x: %.3f\n', ...
    maximum_wheel_speed_all_cases(1));
fprintf('y: %.3f\n', ...
    maximum_wheel_speed_all_cases(2));
fprintf('z: %.3f\n', ...
    maximum_wheel_speed_all_cases(3));

fprintf('\nCases activating a speed limit: %d\n', ...
    number_of_speed_limit_cases);

fprintf('\nFinal bias-error magnitude [deg/s]:\n');
fprintf('Mean: %.6f\n', ...
    mean(bias_error_magnitude));
fprintf('Worst: %.6f\n', ...
    max(bias_error_magnitude));

fprintf('\nWorst control-error case: %d\n', ...
    worst_control_case);

fprintf('Its initial attitude [deg]:\n');
fprintf('%.3f  %.3f  %.3f\n', ...
    initial_attitude_history(worst_control_case,:));

fprintf('\nWorst estimation-error case: %d\n', ...
    worst_estimation_case);

%% Plot results
figure;

subplot(4,1,1);

histogram(final_control_error_deg, 15);
grid on;
xlabel('Final control error [deg]');
ylabel('Cases');
title('Estimated-State Monte Carlo Results');

subplot(4,1,2);

histogram(final_estimation_error_deg, 15);
grid on;
xlabel('Final estimation error [deg]');
ylabel('Cases');

subplot(4,1,3);

histogram(valid_settling_times, 15);
grid on;
xlabel('Settling time [s]');
ylabel('Cases');

subplot(4,1,4);

plot(1:number_of_cases, ...
    maximum_wheel_speed_rpm(:,1), '.', ...
    'MarkerSize', 10);

hold on;

plot(1:number_of_cases, ...
    maximum_wheel_speed_rpm(:,2), '.', ...
    'MarkerSize', 10);

plot(1:number_of_cases, ...
    maximum_wheel_speed_rpm(:,3), '.', ...
    'MarkerSize', 10);

yline(6000, '--r', 'Speed limit');

grid on;
xlabel('Case number');
ylabel('Maximum wheel speed [rpm]');

legend('x', 'y', 'z', 'Limit', ...
    'Location', 'best');