function results = simulate_estimated_state_case( ...
    initial_attitude_deg, ...
    inertia_matrix, ...
    Kp, ...
    Kd, ...
    wheel_inertia, ...
    wheel_torque_max, ...
    wheel_speed_max, ...
    gyro_bias_initial, ...
    gyro_noise_std, ...
    gyro_bias_random_walk, ...
    star_tracker_noise_std, ...
    gyro_sample_time, ...
    star_tracker_sample_time, ...
    simulation_duration, ...
    initial_estimation_error_deg)
%SIMULATE_ESTIMATED_STATE_CASE Run one noisy MEKF control case.

sample_time = gyro_sample_time;

time = (0:sample_time:simulation_duration).';
number_of_samples = length(time);

star_tracker_interval = round( ...
    star_tracker_sample_time / sample_time);

command_quaternion = [1; 0; 0; 0];

%% True initial state
true_quaternion = euler_to_quaternion( ...
    deg2rad(initial_attitude_deg(:)));

true_state = [
    true_quaternion;
    0;
    0;
    0;
    0;
    0;
    0
];

true_gyro_bias = gyro_bias_initial(:);

%% Initial estimator state
initial_error_quaternion = ...
    rotation_vector_to_quaternion( ...
        deg2rad(initial_estimation_error_deg(:)));

quaternion_estimate = quaternion_multiply( ...
    true_quaternion, ...
    initial_error_quaternion);

bias_estimate = zeros(3,1);

initial_attitude_sigma = deg2rad(5);
initial_bias_sigma = deg2rad(0.1);

covariance = diag([
    initial_attitude_sigma^2 * ones(3,1);
    initial_bias_sigma^2 * ones(3,1)
]);

%% Allocate result histories
control_error_deg = ...
    zeros(number_of_samples, 1);

estimation_error_deg = ...
    zeros(number_of_samples, 1);

wheel_speed_history = ...
    zeros(number_of_samples, 3);

applied_torque_history = ...
    zeros(number_of_samples, 3);

speed_limited_history = ...
    false(number_of_samples, 3);

%% Initial measurements
gyro_measurement_value = gyro_measurement( ...
    true_state(5:7), ...
    true_gyro_bias, ...
    gyro_noise_std);

star_tracker_value = star_tracker_measurement( ...
    true_state(1:4), ...
    star_tracker_noise_std);

%% Initial MEKF correction
[quaternion_estimate, ...
 bias_estimate, ...
 covariance] = mekf_update( ...
    quaternion_estimate, ...
    bias_estimate, ...
    covariance, ...
    star_tracker_value, ...
    star_tracker_noise_std);

%% Discrete closed-loop simulation
for k = 1:number_of_samples
    %% Record control error
    control_error_quaternion = quaternion_error( ...
        command_quaternion, ...
        true_state(1:4));

    control_error_scalar = min(1, max(-1, ...
        abs(control_error_quaternion(1))));

    control_error_deg(k) = rad2deg( ...
        2 * acos(control_error_scalar));

    %% Record estimation error
    estimation_error_quaternion = quaternion_error( ...
        true_state(1:4), ...
        quaternion_estimate);

    estimation_error_scalar = min(1, max(-1, ...
        abs(estimation_error_quaternion(1))));

    estimation_error_deg(k) = rad2deg( ...
        2 * acos(estimation_error_scalar));

    wheel_speed_history(k,:) = ...
        true_state(8:10).';

    %% Estimated angular velocity
    estimated_omega = ...
        gyro_measurement_value ...
        - bias_estimate;

    %% Estimated-state controller
    [~, requested_spacecraft_torque] = ...
        pd_controller_quaternion( ...
            command_quaternion, ...
            quaternion_estimate, ...
            estimated_omega, ...
            Kp, ...
            Kd, ...
            wheel_torque_max);

    [applied_torque, ~, ~, speed_limited] = ...
        reaction_wheel_actuator( ...
            requested_spacecraft_torque, ...
            true_state(8:10), ...
            wheel_inertia, ...
            wheel_torque_max, ...
            wheel_speed_max);

    applied_torque_history(k,:) = ...
        applied_torque.';

    speed_limited_history(k,:) = ...
        speed_limited.';

    if k == number_of_samples
        break;
    end

    %% Propagate true spacecraft
    true_state = rk4_reaction_wheel_step( ...
        true_state, ...
        requested_spacecraft_torque, ...
        sample_time, ...
        inertia_matrix, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max);

    %% Propagate true gyro bias
    true_gyro_bias = update_gyro_bias( ...
        true_gyro_bias, ...
        gyro_bias_random_walk, ...
        sample_time);

    %% Propagate MEKF using current gyro sample
    [quaternion_estimate, ...
     bias_estimate, ...
     covariance] = mekf_propagate( ...
        quaternion_estimate, ...
        bias_estimate, ...
        covariance, ...
        gyro_measurement_value, ...
        sample_time, ...
        gyro_noise_std, ...
        gyro_bias_random_walk);

    %% Generate next gyro measurement
    gyro_measurement_value = gyro_measurement( ...
        true_state(5:7), ...
        true_gyro_bias, ...
        gyro_noise_std);

    %% Star-tracker update
    star_tracker_available = ...
        mod(k, star_tracker_interval) == 0;

    if star_tracker_available
        star_tracker_value = star_tracker_measurement( ...
            true_state(1:4), ...
            star_tracker_noise_std);

        [quaternion_estimate, ...
         bias_estimate, ...
         covariance] = mekf_update( ...
            quaternion_estimate, ...
            bias_estimate, ...
            covariance, ...
            star_tracker_value, ...
            star_tracker_noise_std);
    end
end

%% Performance calculations
wheel_speed_rpm = ...
    wheel_speed_history * 60 / (2*pi);

settling_threshold_deg = 0.5;
settling_time = NaN;

for k = 1:number_of_samples
    if all(control_error_deg(k:end) ...
            <= settling_threshold_deg)
        settling_time = time(k);
        break;
    end
end

results.final_control_error_deg = ...
    control_error_deg(end);

results.final_estimation_error_deg = ...
    estimation_error_deg(end);

results.rms_estimation_error_deg = sqrt(mean( ...
    estimation_error_deg.^2));

results.maximum_wheel_speed_rpm = ...
    max(abs(wheel_speed_rpm), [], 1);

results.maximum_applied_torque = ...
    max(abs(applied_torque_history), [], 1);

results.speed_limit_activated = ...
    any(speed_limited_history, 1);

results.settling_time = settling_time;

results.final_bias_error_deg_s = rad2deg( ...
    bias_estimate - true_gyro_bias);

end