%% Closed-Loop Attitude Control Using MEKF Estimates

clear;
clc;
close all;

%% Load parameters
init_attitude_3axis;
init_reaction_wheels;
init_sensor_models;

%% Simulation timing
sample_time = gyro_sample_time;
time = (0:sample_time:t_final).';
number_of_samples = length(time);

star_tracker_interval = round( ...
    star_tracker_sample_time / sample_time);

%% True initial state
true_initial_attitude = deg2rad([30; -20; 15]);

true_initial_quaternion = ...
    euler_to_quaternion(true_initial_attitude);

command_quaternion = ...
    euler_to_quaternion(attitude_cmd);

true_state = [
    true_initial_quaternion;
    omega0;
    0;
    0;
    0
];

true_gyro_bias = gyro_bias_initial;

%% Initial estimator state
initial_estimation_error = deg2rad([2; -1; 1.5]);

initial_error_quaternion = ...
    rotation_vector_to_quaternion( ...
        initial_estimation_error);

quaternion_estimate = quaternion_multiply( ...
    true_initial_quaternion, ...
    initial_error_quaternion);

bias_estimate = [0; 0; 0];

initial_attitude_sigma = deg2rad(5);
initial_bias_sigma = deg2rad(0.1);

covariance = diag([
    initial_attitude_sigma^2 * ones(3,1);
    initial_bias_sigma^2 * ones(3,1)
]);

%% Allocate histories
true_state_history = ...
    zeros(number_of_samples, 10);

true_bias_history = ...
    zeros(number_of_samples, 3);

gyro_measurement_history = ...
    zeros(number_of_samples, 3);

star_tracker_history = ...
    NaN(number_of_samples, 4);

quaternion_estimate_history = ...
    zeros(number_of_samples, 4);

bias_estimate_history = ...
    zeros(number_of_samples, 3);

covariance_diagonal_history = ...
    zeros(number_of_samples, 6);

requested_torque_history = ...
    zeros(number_of_samples, 3);

applied_torque_history = ...
    zeros(number_of_samples, 3);

speed_limited_history = ...
    false(number_of_samples, 3);

%% Initial sensor measurements
gyro_measurement_value = gyro_measurement( ...
    true_state(5:7), ...
    true_gyro_bias, ...
    gyro_noise_std);

star_tracker_value = star_tracker_measurement( ...
    true_state(1:4), ...
    star_tracker_noise_std);

%% Initial star-tracker correction
[quaternion_estimate, ...
 bias_estimate, ...
 covariance] = mekf_update( ...
    quaternion_estimate, ...
    bias_estimate, ...
    covariance, ...
    star_tracker_value, ...
    star_tracker_noise_std);

%% Store initial values
true_state_history(1,:) = true_state.';
true_bias_history(1,:) = true_gyro_bias.';

gyro_measurement_history(1,:) = ...
    gyro_measurement_value.';

star_tracker_history(1,:) = ...
    star_tracker_value.';

quaternion_estimate_history(1,:) = ...
    quaternion_estimate.';

bias_estimate_history(1,:) = ...
    bias_estimate.';

covariance_diagonal_history(1,:) = ...
    diag(covariance).';

%% Discrete closed-loop simulation
for k = 1:number_of_samples
    %% Controller uses estimated attitude and estimated rate
    estimated_omega = ...
        gyro_measurement_history(k,:).' ...
        - bias_estimate;

    [~, requested_spacecraft_torque] = ...
        pd_controller_quaternion( ...
            command_quaternion, ...
            quaternion_estimate, ...
            estimated_omega, ...
            Kp, ...
            Kd, ...
            wheel_torque_max);

    requested_torque_history(k,:) = ...
        requested_spacecraft_torque.';

    [applied_torque, ~, ~, speed_limited] = ...
        reaction_wheel_actuator( ...
            requested_spacecraft_torque, ...
            true_state(8:10), ...
            wheel_inertia, ...
            wheel_torque_max, ...
            wheel_speed_max);

    applied_torque_history(k,:) = ...
        applied_torque.';

    speed_limited_history(k,:) = ...
        speed_limited.';

    if k == number_of_samples
        break;
    end

    %% Propagate true spacecraft and wheels
    true_state = rk4_reaction_wheel_step( ...
        true_state, ...
        requested_spacecraft_torque, ...
        sample_time, ...
        I, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max);

    %% Propagate true gyro bias
    true_gyro_bias = update_gyro_bias( ...
        true_gyro_bias, ...
        gyro_bias_random_walk, ...
        sample_time);

    %% Generate the next gyro measurement
    next_gyro_measurement = gyro_measurement( ...
        true_state(5:7), ...
        true_gyro_bias, ...
        gyro_noise_std);

    %% Propagate MEKF using the previous gyro sample
    [quaternion_estimate, ...
     bias_estimate, ...
     covariance] = mekf_propagate( ...
        quaternion_estimate, ...
        bias_estimate, ...
        covariance, ...
        gyro_measurement_history(k,:).', ...
        sample_time, ...
        gyro_noise_std, ...
        gyro_bias_random_walk);

    %% Generate and process star-tracker measurement
    star_tracker_available = ...
        mod(k, star_tracker_interval) == 0;

    if star_tracker_available
        next_star_tracker_measurement = ...
            star_tracker_measurement( ...
                true_state(1:4), ...
                star_tracker_noise_std);

        [quaternion_estimate, ...
         bias_estimate, ...
         covariance] = mekf_update( ...
            quaternion_estimate, ...
            bias_estimate, ...
            covariance, ...
            next_star_tracker_measurement, ...
            star_tracker_noise_std);
    else
        next_star_tracker_measurement = ...
            [NaN; NaN; NaN; NaN];
    end

    %% Store next sample
    true_state_history(k+1,:) = true_state.';
    true_bias_history(k+1,:) = true_gyro_bias.';

    gyro_measurement_history(k+1,:) = ...
        next_gyro_measurement.';

    star_tracker_history(k+1,:) = ...
        next_star_tracker_measurement.';

    quaternion_estimate_history(k+1,:) = ...
        quaternion_estimate.';

    bias_estimate_history(k+1,:) = ...
        bias_estimate.';

    covariance_diagonal_history(k+1,:) = ...
        diag(covariance).';
end

%% Extract and convert results
true_quaternion_history = ...
    true_state_history(:,1:4);

true_omega = true_state_history(:,5:7);
wheel_speed = true_state_history(:,8:10);

true_attitude_deg = ...
    zeros(number_of_samples, 3);

attitude_control_error_deg = ...
    zeros(number_of_samples, 1);

attitude_estimation_error_deg = ...
    zeros(number_of_samples, 1);

for k = 1:number_of_samples
    true_attitude_deg(k,:) = rad2deg( ...
        quaternion_to_euler( ...
        true_quaternion_history(k,:).')).';

    control_error_quaternion = quaternion_error( ...
        command_quaternion, ...
        true_quaternion_history(k,:).');

    control_error_scalar = min(1, max(-1, ...
        abs(control_error_quaternion(1))));

    attitude_control_error_deg(k) = rad2deg( ...
        2 * acos(control_error_scalar));

    estimation_error_quaternion = quaternion_error( ...
        true_quaternion_history(k,:).', ...
        quaternion_estimate_history(k,:).');

    estimation_error_scalar = min(1, max(-1, ...
        abs(estimation_error_quaternion(1))));

    attitude_estimation_error_deg(k) = rad2deg( ...
        2 * acos(estimation_error_scalar));
end

true_omega_deg_s = rad2deg(true_omega);

wheel_speed_rpm = ...
    wheel_speed * 60 / (2*pi);

bias_estimation_error_deg_s = rad2deg( ...
    bias_estimate_history - true_bias_history);

%% Performance calculations
final_control_error_deg = ...
    attitude_control_error_deg(end);

rms_estimation_error_deg = sqrt(mean( ...
    attitude_estimation_error_deg.^2));

final_estimation_error_deg = ...
    attitude_estimation_error_deg(end);

maximum_applied_torque = ...
    max(abs(applied_torque_history), [], 1);

maximum_wheel_speed_rpm = ...
    max(abs(wheel_speed_rpm), [], 1);

speed_limit_activated = ...
    any(speed_limited_history, 1);

tolerance_deg = 0.5;
settling_time = NaN;

for k = 1:number_of_samples
    if all(attitude_control_error_deg(k:end) <= tolerance_deg)
        settling_time = time(k);
        break;
    end
end

%% Display results
fprintf('\nEstimated-state closed-loop results:\n');

fprintf('\nFinal control error: %.6f deg\n', ...
    final_control_error_deg);

fprintf('Final estimation error: %.6f deg\n', ...
    final_estimation_error_deg);

fprintf('RMS estimation error: %.6f deg\n', ...
    rms_estimation_error_deg);

fprintf('\nMaximum applied torque [N m]:\n');
fprintf('x: %.6f\n', maximum_applied_torque(1));
fprintf('y: %.6f\n', maximum_applied_torque(2));
fprintf('z: %.6f\n', maximum_applied_torque(3));

fprintf('\nMaximum wheel speed [rpm]:\n');
fprintf('x: %.3f\n', maximum_wheel_speed_rpm(1));
fprintf('y: %.3f\n', maximum_wheel_speed_rpm(2));
fprintf('z: %.3f\n', maximum_wheel_speed_rpm(3));

fprintf('\nFinal bias-estimation error [deg/s]:\n');
fprintf('x: %.6f\n', bias_estimation_error_deg_s(end,1));
fprintf('y: %.6f\n', bias_estimation_error_deg_s(end,2));
fprintf('z: %.6f\n', bias_estimation_error_deg_s(end,3));

fprintf('\nWheel-speed limit activated [x y z]:\n');
disp(speed_limit_activated);

if isnan(settling_time)
    fprintf('The attitude did not settle within %.2f deg.\n', ...
        tolerance_deg);
else
    fprintf('Settling time within %.2f deg: %.3f s\n', ...
        tolerance_deg, settling_time);
end

%% Plot results
figure;

subplot(4,1,1);
plot(time, true_attitude_deg, 'LineWidth', 1.2);
grid on;
ylabel('Attitude [deg]');
title('Closed-Loop Control Using MEKF Estimates');
legend('Roll', 'Pitch', 'Yaw', 'Location', 'best');

subplot(4,1,2);
plot(time, attitude_estimation_error_deg, ...
    'LineWidth', 1.1);
grid on;
ylabel('Estimation error [deg]');

subplot(4,1,3);
plot(time, wheel_speed_rpm, 'LineWidth', 1.1);
grid on;
ylabel('Wheel speed [rpm]');
legend('\Omega_x', '\Omega_y', '\Omega_z', ...
    'Location', 'best');

subplot(4,1,4);
plot(time, applied_torque_history, ...
    'LineWidth', 1.0);
grid on;
xlabel('Time [s]');
ylabel('Torque [N m]');
legend('\tau_x', '\tau_y', '\tau_z', ...
    'Location', 'best');