function results = simulate_monte_carlo_attitude_case( ...
    initial_attitude_deg, ...
    inertia_matrix, ...
    Kp, ...
    Kd, ...
    wheel_inertia, ...
    wheel_torque_max, ...
    wheel_speed_max, ...
    sample_time, ...
    simulation_duration)
%SIMULATE_MONTE_CARLO_ATTITUDE_CASE Run one attitude-control case.

command_quaternion = [1; 0; 0; 0];

initial_quaternion = euler_to_quaternion( ...
    deg2rad(initial_attitude_deg(:)));

state = [
    initial_quaternion;
    0;
    0;
    0;
    0;
    0;
    0
];

time = (0:sample_time:simulation_duration).';
number_of_samples = length(time);

pointing_error_deg = zeros(number_of_samples, 1);
wheel_speed_history = zeros(number_of_samples, 3);
torque_history = zeros(number_of_samples, 3);

for k = 1:number_of_samples
    %% Pointing error
    error_quaternion = quaternion_error( ...
        command_quaternion, ...
        state(1:4));

    error_scalar = min(1, max(-1, ...
        abs(error_quaternion(1))));

    pointing_error_deg(k) = ...
        rad2deg(2 * acos(error_scalar));

    wheel_speed_history(k,:) = state(8:10).';

    %% Controller
    [~, requested_torque] = ...
        pd_controller_quaternion( ...
            command_quaternion, ...
            state(1:4), ...
            state(5:7), ...
            Kp, ...
            Kd, ...
            wheel_torque_max);

    [applied_torque, ~] = ...
        reaction_wheel_actuator( ...
            requested_torque, ...
            state(8:10), ...
            wheel_inertia, ...
            wheel_torque_max, ...
            wheel_speed_max);

    torque_history(k,:) = applied_torque.';

    if k == number_of_samples
        break;
    end

    state = rk4_reaction_wheel_step( ...
        state, ...
        requested_torque, ...
        sample_time, ...
        inertia_matrix, ...
        wheel_inertia, ...
        wheel_torque_max, ...
        wheel_speed_max);
end

%% Calculate settling time
settling_threshold_deg = 0.5;
settling_time = NaN;

for k = 1:number_of_samples
    if all(pointing_error_deg(k:end) ...
            <= settling_threshold_deg)
        settling_time = time(k);
        break;
    end
end

%% Package results
results.final_error_deg = ...
    pointing_error_deg(end);

results.maximum_error_deg = ...
    max(pointing_error_deg);

results.maximum_wheel_speed_rpm = ...
    max(abs(wheel_speed_history), [], 1) ...
    * 60 / (2*pi);

results.maximum_torque = ...
    max(abs(torque_history), [], 1);

results.settling_time = settling_time;

results.wheel_speed_limit_activated = any( ...
    abs(wheel_speed_history) ...
    >= wheel_speed_max.' * (1 - 1e-9), 1);

results.time = time;
results.pointing_error_deg = pointing_error_deg;

end