function [torque_body, force_body] = ...
    solar_radiation_pressure_torque( ...
        sun_direction_inertial, ...
        quaternion, ...
        solar_pressure, ...
        reflectivity_coefficient, ...
        illuminated_area, ...
        centre_of_pressure_offset_body, ...
        illumination_factor)
%SOLAR_RADIATION_PRESSURE_TORQUE
% Calculate a simplified solar-radiation-pressure force and torque.
%
% sun_direction_inertial points from the spacecraft toward the Sun.
% Radiation force acts away from the Sun.
%
% illumination_factor:
%   1 = fully illuminated
%   0 = eclipse

sun_direction_norm = norm(sun_direction_inertial);

if sun_direction_norm < 1e-12 || illumination_factor <= 0
    force_body = [0; 0; 0];
    torque_body = [0; 0; 0];
    return;
end

sun_unit_inertial = ...
    sun_direction_inertial / sun_direction_norm;

%% Force acts away from the Sun
force_inertial = ...
    -illumination_factor ...
    * solar_pressure ...
    * reflectivity_coefficient ...
    * illuminated_area ...
    * sun_unit_inertial;

%% Convert force to body axes
body_to_inertial = ...
    quaternion_to_rotation_matrix(quaternion);

force_body = ...
    body_to_inertial.' * force_inertial;

%% Torque about the centre of mass
torque_body = cross( ...
    centre_of_pressure_offset_body, ...
    force_body);

end